# dbt Google Trends - Projet structuré selon les bonnes pratiques
# https://docs.getdbt.com/best-practices/how-we-structure

name: "dbt-testing"
version: "1.0.0"
config-version: 2

profile: "dbt-testing"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt-testing:
    # Staging: vues légères, transformations minimales (renommage, types)
    staging:
      +materialized: view

    # Intermediate: vues pour transformations complexes
    intermediate:
      +materialized: view

    # Marts: tables business-ready par domaine
    marts:
      +materialized: table
